
language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: SashaRepin2/Lab_6_TRPO  
    branch: master
    tags: true
