language: python
python: 3.8
script:
  echo Starting test and build...
branches:
  only:
  - master
  - dev
import:
- source: travis/prerelease.yml
  if: branch = dev
- source: travis/release.yml
  if: branch = master
